# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "83684d0880e75de5e9e6a50edc09646e"
name = "Neolook-shopifi"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[webhooks]
api_version = "2026-04"
